/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formulários;

/**
 *
 * @author CAMARGO
 */
public class Calculo extends javax.swing.JPanel {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_N1 = new javax.swing.JTextField();
        txt_N2 = new javax.swing.JTextField();
        txt_Resultados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonSoma = new javax.swing.JButton();
        buttonSoma1 = new javax.swing.JButton();
        buttonSoma2 = new javax.swing.JButton();
        buttonSoma3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(205, 142, 205));
        jLabel1.setText("Número 1");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(205, 142, 205));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Número 2");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(205, 142, 205));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultados");

        txt_N1.setBackground(new java.awt.Color(246, 254, 255));
        txt_N1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_N1ActionPerformed(evt);
            }
        });

        txt_N2.setBackground(new java.awt.Color(246, 254, 255));
        txt_N2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_N2ActionPerformed(evt);
            }
        });

        txt_Resultados.setBackground(new java.awt.Color(246, 254, 255));
        txt_Resultados.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_Resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ResultadosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 152, 213));
        jLabel4.setText("CALCULADORA");

        buttonSoma.setBackground(new java.awt.Color(242, 233, 242));
        buttonSoma.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        buttonSoma.setForeground(new java.awt.Color(123, 87, 137));
        buttonSoma.setText("+");
        buttonSoma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonSoma1.setBackground(new java.awt.Color(242, 233, 242));
        buttonSoma1.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        buttonSoma1.setForeground(new java.awt.Color(123, 87, 137));
        buttonSoma1.setText(".");
        buttonSoma1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSoma1ActionPerformed(evt);
            }
        });

        buttonSoma2.setBackground(new java.awt.Color(242, 233, 242));
        buttonSoma2.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        buttonSoma2.setForeground(new java.awt.Color(123, 87, 137));
        buttonSoma2.setText("-");
        buttonSoma2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonSoma3.setBackground(new java.awt.Color(242, 233, 242));
        buttonSoma3.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        buttonSoma3.setForeground(new java.awt.Color(123, 87, 137));
        buttonSoma3.setText(":");
        buttonSoma3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttonSoma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSoma3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_N1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSoma2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSoma3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_N2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Resultados))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(buttonSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSoma2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSoma1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSoma3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_N1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_N1ActionPerformed

    private void txt_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_N2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_N2ActionPerformed

    private void txt_ResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ResultadosActionPerformed

    private void buttonSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSoma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSoma1ActionPerformed

    private void buttonSoma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSoma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSoma3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSoma;
    private javax.swing.JButton buttonSoma1;
    private javax.swing.JButton buttonSoma2;
    private javax.swing.JButton buttonSoma3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_N1;
    private javax.swing.JTextField txt_N2;
    private javax.swing.JTextField txt_Resultados;
    // End of variables declaration//GEN-END:variables
}
